### ISSUE TITLE
您好！请问有部署脚本或者过程详细说明吗

### ISSUE THREAD

**Issue by wagnzi** [INET-RC/GeoMX#2]
您好，docker部署过程有详细说明吗，文档里只说明了怎么连接不同的docker节点，没有说怎么启动分布式训练geomx

**Comment by Lizonghang** [comment]
Hello, wagnzi:

Please try:

```shell
sudo docker run -it --rm --name geomx lizonghango00o1/geomx:cpu-only bash
cd GeoMX/scripts/cpu && bash run_vanilla_hips.sh
```

More details are [here](https://github.com/INET-RC/GeoMX/blob/main/README.md).
